export const IMAGE_CLASSIFICATION_SUCCESS = "IMAGE_CLASSIFICATION_SUCCESS";
export const IMAGE_CLASSIFICATION_LOADING = "IMAGE_CLASSIFICATION_LOADING";
export const IMAGE_CLASSIFICATION_FAILURE = "IMAGE_CLASSIFICATION_FAILURE";
