import {
  IMAGE_CLASSIFICATION_SUCCESS,
  IMAGE_CLASSIFICATION_LOADING,
  IMAGE_CLASSIFICATION_FAILURE,
} from "store/constants/imageClassificationConstants";

export {
  IMAGE_CLASSIFICATION_SUCCESS,
  IMAGE_CLASSIFICATION_LOADING,
  IMAGE_CLASSIFICATION_FAILURE,
};
